# Generated by Django 5.1.1 on 2024-09-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('signature', models.CharField(default="Are you the strongest because you're Satoru Gojo? Or are you Satoru Gojo because you're the strongest?", max_length=140)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
